import type { CapabilityContract } from "@brivya/core";
import {
  projectCapability,
  validateCapabilityProjection,
  type CapabilityProjection,
} from "@brivya/distribution";
import type {
  SemanticExperience,
  SemanticRenderResult,
} from "@brivya/experience";
import { validateSemanticExperience } from "@brivya/experience";

export interface WeChatBusinessMetadata {
  id: string;
  name: string;
  description: string;
  skillName: string;
  relatedPage?: string;
}

export interface WeChatAiPackage {
  artifacts: Readonly<Record<string, string>>;
  projections: readonly CapabilityProjection[];
  render: SemanticRenderResult;
}

export function renderWeChatAiPackage(
  business: WeChatBusinessMetadata,
  capabilities: readonly CapabilityContract[],
  experience: SemanticExperience,
): WeChatAiPackage {
  const experienceValidation = validateSemanticExperience(experience, {
    capabilities,
  });
  if (experienceValidation.status === "fail") {
    throw new Error("SemanticExperience is not valid for WeChat projection.");
  }

  const projections = capabilities.map(projectCapability);
  for (let index = 0; index < capabilities.length; index += 1) {
    const canonical = capabilities[index];
    const projected = projections[index];
    if (!canonical || !projected) continue;
    const conformance = validateCapabilityProjection(canonical, projected);
    if (conformance.status === "fail") {
      throw new Error(`Unsafe WeChat projection for ${canonical.id}.`);
    }
  }

  const componentPath = `components/${experience.metadata.id}-card/index`;
  const bindings = (experience.actions ?? []).map((action) => ({
    semanticAction: action.id,
    capability: action.capability,
    platformAction:
      action.type === "capability" && action.capability
        ? `api/call:${action.capability}`
        : `follow-up:${action.id}`,
  }));

  const render: SemanticRenderResult = {
    experience: experience.metadata.id,
    renderer: "wechat-ai",
    profileVersion: "0.1.0",
    bindings,
    artifacts: [
      `${componentPath}.json`,
      `${componentPath}.wxml`,
      `${componentPath}.js`,
      `${componentPath}.wxss`,
    ],
  };

  const mcp = {
    apis: projections.map((item) => ({
      name: item.id,
      description:
        `Brivya capability ${item.id}. Runtime safety remains authoritative.`,
      inputSchema: item.inputSchema,
      outputSchema: item.outputSchema,
      _meta: {
        ui: { componentPath },
        brivya: {
          version: item.version,
          risk: item.risk,
          approval: item.approval,
          permissions: item.permissions,
          idempotencyRequired: item.idempotencyRequired,
        },
      },
    })),
    components: [
      {
        path: componentPath,
        relatedPage: business.relatedPage ?? "/pages/home/home",
      },
    ],
  };

  const skill = [
    "---",
    `name: ${business.skillName}`,
    `description: ${business.description}`,
    'platform: ["wechat-miniprogram"]',
    "---",
    "",
    `# ${business.name}`,
    "",
    "## Safety",
    "- WeChat platform identity is identity context only, not delegation.",
    "- Mutation authority is enforced by Brivya BusinessRuntime.",
    "- UI confirmation never replaces Brivya ApprovalRecord.",
    "",
    "## Capability bindings",
    ...projections.map((item) => `- ${item.id}@${item.version}`),
  ].join("\n");

  const apiDescriptor = {
    mode: "runtime-bridge",
    trustedIdentitySource: "platform-injected",
    clientSuppliedIdentity: "forbidden",
    delegation: "explicit",
    capabilities: projections.map((item) => item.id),
  };

  const componentDescriptor = {
    experience: experience.metadata.id,
    resource: experience.view.resource ?? null,
    bindings,
    dataContract: {
      structuredContent: "business-data",
      _meta: "render-only-data",
    },
  };

  const appPatch = {
    agent: {
      skills: [
        {
          name: business.skillName,
          description: business.description,
          path: `skills/${business.skillName}`,
        },
      ],
    },
  };

  return {
    projections,
    render,
    artifacts: {
      "SKILL.md": skill,
      "mcp.json": JSON.stringify(mcp, null, 2),
      "apis/runtime-bridge.json": JSON.stringify(apiDescriptor, null, 2),
      `${componentPath}.json`: JSON.stringify(componentDescriptor, null, 2),
      `${componentPath}.wxml`: "<view><!-- generated by Brivya WeChat renderer --></view>",
      `${componentPath}.js`: "module.exports = { generatedBy: 'brivya' };",
      `${componentPath}.wxss`: "/* platform-native presentation generated by profile */",
      "app-registration.patch.json": JSON.stringify(appPatch, null, 2),
    },
  };
}
